### ISSUE TITLE
Set a default value for docker_ucp_host_address

### ISSUE THREAD

**Issue by ioggstream** [atosatto/ansible-datacenter#1]
Running the playbook, I expect

```
docker_ucp_host_address to be set (eg. as the first host)
```

Instead:
- it's undefined
- the playbook fails (on digitalocean).

I'll try to fix it setting the variable in the playbook, but I think that's something that should come up ootb.

Thx for your nice playbook + Peace,
R:

**Comment by ioggstream** [comment]
Edit: it seems it's a fault of vagrant-ansible provisioner that doesn't retain facts between hosts ;) sorry + thx again. 

R.

**Comment by atosatto** [comment]
Hi @ioggstream, thank you for getting in touch with me!

Have you tried to add the `ansible.limit = "all"` configuration to your vagrant-ansible provisioner?
Can I help you to make this role work with your Ansible setup?

**Comment by ioggstream** [comment]
Hi @atosatto,

the `ansible.limit = "all"` seem to do the job, you may need to re-issue `vagrant provision` in case of errors.

There's still an issue using `docker_ucp_host_address` when provisioning worker nodes: I'll send you the patches asap.

Thx+Peace,
R.
